- name: ollama_chat/qwen2.5-coder:7b
  edit_format: diff
  weak_model_name: ollama_chat/qwen2.5-coder:7b
  use_repo_map: true
  editor_model_name: ollama_chat/qwen2.5-coder:7b
  editor_edit_format: editor-diff
  extra_params:
    num_ctx: 16384

- name: ollama_chat/cogito:8b
  edit_format: diff
  weak_model_name: ollama_chat/cogito:8b
  use_repo_map: true
  editor_model_name: ollama_chat/cogito:8b
  editor_edit_format: editor-diff
  extra_params:
    num_ctx: 16384
