tap "docker/tap"
tap "minamijoyo/hcledit"
tap "minamijoyo/myaws"
tap "minamijoyo/tfedit"
tap "minamijoyo/tfmigrate"
tap "minamijoyo/tfschema"
tap "minamijoyo/tfupdate"

brew "awscli"
brew "git"
brew "gnu-sed"
brew "mas"
brew "mise"
brew "rcm"
brew "reattach-to-user-namespace"
brew "sqlparse"
brew "the_silver_searcher"
brew "tig"
brew "tree"
brew "vim"
brew "watch"
brew "zplug"
brew "minamijoyo/hcledit/hcledit"
brew "minamijoyo/myaws/myaws"
brew "minamijoyo/tfedit/tfedit"
brew "minamijoyo/tfmigrate/tfmigrate"
brew "minamijoyo/tfschema/tfschema"
brew "minamijoyo/tfupdate/tfupdate"

cask "1password"
cask "1password-cli"
cask "aws-vault-binary"
cask "dash"
cask "docker-desktop"
cask "git-credential-manager"
cask "google-japanese-ime"
cask "iterm2"
cask "licecap"
cask "raycast"
cask "docker/tap/sbx"
cask "session-manager-plugin"
cask "slack"
cask "zoom"

mas "Keynote", id: 409183694
mas "Monosnap", id: 540348655
