[settings]
minimum_release_age = "7d"
lockfile = true
lockfile_platforms = ["macos-arm64"]
disable_backends = ["asdf", "vfox"]
idiomatic_version_file_enable_tools = [
  "go",
  "node",
  "opentofu",
  "poetry",
  "python",
  "ruby",
  "terraform",
]

[settings.ruby]
compile = false

[tools]
go = "1.26"
node = "24"
opentofu = "1.12"
poetry = "2.4.1"
python = "3.13"
ruby = "3.4"
terraform = "1.15"
